postgres:
  image: postgres:latest
  container_name: postgres-account-demo
  environment:
    - "TZ=Europe/Amsterdam"
    - "POSTGRES_USER=lagom"
    - "POSTGRES_PASSWORD=lagom"
  ports:
    - "5432:5432"  # credentials (lagom:lagom)
